### PR TITLE
Task 5 implemented

### PR DESCRIPTION
**Pull request by jegius**
- [x] 1 - File serverless.yml contains configuration for importProductsFile function
- [x] 3 - The importProductsFile lambda function returns a correct response which can be used to upload a file into the S3 bucket
- [x] 4 - Frontend application is integrated with importProductsFile lambda
- [x] 5 - The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda

Additional (optional) tasks
api - https://lirnkhspqk.execute-api.eu-west-1.amazonaws.com

[link to frontend](https://d20wes0bg8lspj.cloudfront.net/)
- [x] +1 - async/await is used in lambda functions
- [ ] +1 - importProductsFile lambda is covered by unit tests (aws-sdk-mock can be used to mock S3 methods - https://www.npmjs.com/package/aws-sdk-mock)
- [x] +1 - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into parsed folder, and then deleted from uploaded folder)

### CODE REVIEW

**Comment by shurygindv** [comment]
@jegius, could you give a front-end origin?

add test files for lambda functions a little bit, we know you can)

**Comment by jegius** [comment]
https://d20wes0bg8lspj.cloudfront.net/ - link to frontend but put is not working. I don't know why. I spended a lot of time when I tried to fix it, but I didn't fix it. I Looked at other PR and don't see the defference.

**Comment by shurygindv** [comment]
is the correct endpoint for backend GET `getSignedUrl`: http://g0s98h1vka.execute-api.eu-west-1.amazonaws.com/dev/import ?) got: `Internal Server Error` with `name` query, give more details, I didn't find it on PL) try to help

**Comment by OlgaGnatenko** [comment]
On some reason frontend returns 400 when uploading a file :( 
"import" endpoint works correctly for me (the link is https://lirnkhspqk.execute-api.eu-west-1.amazonaws.com/dev/import, right?).

**Comment by OlgaGnatenko** [comment]
One more question - are you moving the file to "parsed" folder and deleting it in "uploaded" folder? I wasn't able to find the code for deleting the file.

**Pull request merged**
